### ISSUE TITLE
Very easy to use, solved my big trouble

### ISSUE THREAD

**Issue by echo0708** [ha0z1/idmp#36]
非常好用，我们所有的接口都依赖 getUserInfo 返回的数据，之前用了一个全局 cache 缓存用户数据，但有两个问题，一个是页面加载的时候，getUserInfo 没有返回，后续请求已经同时发出了，造成 getUserInfo 多次发送，第二个是不好做缓存过期。
这个库的确很优雅地解决了！

看文档中，缓存斐波拉契数列也很惊艳，但有个问题，使用 idmp 包装后变成了 Promise 函数，就不能同步调用了，而且每次创建 Promise 函数也有开销吧？

**Comment by haozi** [comment]
If supporting both sync and asyn functions at the same time, it would increase the code size and complexity. Design compromises had to be made.

Any synchronous call can be easily converted to an asynchronous call, so it is compatible.

Async function is one of the most important capabilities of JavaScript. The browser core team has done the most optimized work, the overhead can be ignored.

Most of idmp's application scenarios involve network IO processing, which is limited by the speed of light, with an extreme limit of several tens of ms, unless you live next to the machine room. Compared to a few CPU clock cycles locally, it is hundreds of orders of magnitude slower.

如果同时兼容同步函数和异步函数，会增加代码量，并增加复杂度，设计时做了取舍。
任何同步的调用都可以轻松地转换成异步调用，所以是能兼容的。
async function 是 js 最重要的能力没有之一，浏览器底层做了最极致的优化，开销可以忽略。
idmp 大部分应用场景是处理网络 IO, 受限于光速，这个速度的极限也在几十 ms，除非你家住在机房旁边。相对于本地的几个 CPU 时钟，差了几百个数量级
