### ISSUE TITLE
does not support commonjs?

### ISSUE THREAD

**Issue by popmanhe** [ha0z1/idmp#43]
idmp is so good and solve my issues. 

But it does not seem to support commonjs?

If you just put this one line in a js file and run it 

`const idmp = require('idmp');`

You got this error,

```
const idmp = require('idmp');
             ^

Error [ERR_REQUIRE_ESM]: require() of ES Module D:\temp\test\node_modules\idmp\dist\index.js from D:\temp\test\index.js not supported.
Instead change the require of D:\temp\test\node_modules\idmp\dist\index.js in D:\temp\test\index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (D:\temp\test\index.js:1:14) {
  code: 'ERR_REQUIRE_ESM'
}
```
It always looks for esm module, even in package.json, main points to cjs file. I don't know why it is.

Could you take a look at this, please?

**Comment by haozi** [comment]
try to use `require('dist/index.browser.umd.js')`
https://unpkg.com/browse/idmp@1.12.4/dist/index.browser.umd.js

the default entry is ESM

**Comment by haozi** [comment]
Thanks for your MR, this has been merged, but it is still recommended that you upgrade the backend code to ESM. The `idmp` 2.x version may consider removing CommonJS support.
